import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";
import Footer from "./components/Footer";
import Navbar from "./components/Navbar";

const geistSans = localFont({
	src: "./fonts/GeistVF.woff",
	variable: "--font-geist-sans",
	weight: "100 900",
});
const geistMono = localFont({
	src: "./fonts/GeistMonoVF.woff",
	variable: "--font-geist-mono",
	weight: "100 900",
});

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body>
				<div className="flex flex-col min-h-screen bg-gray-50">
					<header className=" bg-blue-500 p-4 text-white  ">
						<Navbar />
					</header>
					<main className="flex-grow">{children}</main>
					<Footer />
				</div>
			</body>
		</html>
	);
}
